# Generated by Django 5.0.6 on 2024-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
    ]
