# Generated by Django 5.0.6 on 2024-05-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_model_alter_books_price_alter_books_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='price',
            new_name='author',
        ),
    ]
