# Generated by Django 5.0.6 on 2024-05-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='model',
            new_name='book',
        ),
    ]
