# Generated by Django 5.0.6 on 2024-05-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_model_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book',
            new_name='model',
        ),
    ]
