# Generated by Django 5.0.6 on 2024-05-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_book_books_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='model',
            new_name='book',
        ),
    ]
